### ISSUE TITLE
Calling arbitrary function when outline-cycle-emulate-tab

### ISSUE THREAD

**Issue by sg2002** [tj64/outshine#54]
With so many different packages competing for the tab key, can we get a variable where we can put the name of the function that would get called whenever outshine decides to emulate tab?

For my current configuration, I ended up using outline-cycle-emulate-tab 't and replacing [indent-relative](https://github.com/tj64/outshine/blob/master/outshine.el#L2085) with indent-for-tab-command.

**Comment by tj64** [comment]
AFAIK outshine only captures TAB in two situations:
 - outline-on-heading-p gives true
 - bobp gives true AND outline-on-heading-p gives false
otherwise TAB should fall back to its major mode binding.

Using TAB for outline-cycle seems quite logical, I would say. I don't know how if replacing (kbd "TAB") in the keybinding defining macros in outshine with eval'ing a function stored in a custom variable would work anyway (see section Principal Keybindings).

I remember that whatever I did wrt binding TAB, people complained, and the current situation is the result of outshine users contributing a special macro for keybinding with fallback.

Look at line 3850 in outshine.el. The condition there could be extracted into a function that is stored in a custom var. I hope the define-key-with-fallback macro would still work then. 
What would be your alternative condition here?

**Comment by sg2002** [comment]
Well, after some more testing, I don't really need this anymore, since I've found a way to do what I wanted without messing with outshine.

I was trying to setup Yasnippet+Company+Outshine. The best solution I've found was using a custom function that does try yas -> try company, if failed indent. I've modified it to do (outline-cycle) after company. But then I had some weird behavior. What was happening is that starting company expansion with tab, then exiting it with esc, then trying to expand again with tab, folded the outline node. That's what I was able to fix by setting outline-cycle-emulate-tab 't. But this in turn broke tab indentation in outshine buffers, setting it to (indent-relative), which is not nice.

So what I was asking for the ability to change what function is called at that line instead of indent-relative with a variable.

But, since then I've noticed two things. One, the tab-esc-tab thing was only happening when my function was set to tab globally, and setting it to yas-minor-mode-map fixed this. Two, you can actually call, (yas--fallback) manually and this function correctly returns control to outshine. My current code looks like this:
```
(defun do-yas-expand ()
  (let ((yas-fallback-behavior 'return-nil))
    (yas-expand)))

(defun check-expansion ()
  (save-excursion
    (if (looking-at "\\_>") t
      (backward-char 1)
      (if (looking-at "\\.") t
        (backward-char 1)
        (if (looking-at "->") t nil)))))

(defun tab-indent-or-complete ()
  (interactive)
  (if (minibufferp)
      (minibuffer-complete)
    (if (or (not yas-minor-mode)
            (null (do-yas-expand)))
        (if (check-expansion)
            (company-complete-common)
          (yas--fallback)))))

(define-key yas-minor-mode-map [tab] 'tab-indent-or-complete)

```

**Comment by tj64** [comment]
Thanks for sharing! 

I must admit I never used yasnippet due to the TAB war among packages, I recently added a few TEMPO templates to org-dp and liked it quite a lot, its build into Emacs.

**Comment by sg2002** [comment]
No problem. BTW, I've just updated packages, and the last outshine is broken:
```
(file-error "Cannot open load file" "no such file or directory" "outshine-org-cmds")
  require(outshine-org-cmds)
  eval-buffer(#<buffer  *load*> nil "c:/Users/User/.emacs.d/elpa/outshine-20160327.131/outshine.el" nil t)  ; Reading at buffer position 10708
  load-with-code-conversion("c:/Users/User/.emacs.d/elpa/outshine-20160327.131/outshine.el" "c:/Users/User/.emacs.d/elpa/outshine-20160327.131/outshine.el" nil t)
  require(outshine)
  eval((require (quote outshine)) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by tj64** [comment]
Yes, thanks ,the MELPA recipe needs to be fixed, but I somehow messed up ...
