### ISSUE TITLE
Possibly erratic behaviour for outline-move-subtree-up when on last subtree

### ISSUE THREAD

**Issue by priyadarshan** [tj64/outshine#60]
Hello,

I am seeing a possibly erratic behaviour for `outline-move-subtree-up` when on last subtree.

Being in `emacs-lisp-mode`, using the example below with `outshine` active,

```
;;; Level 1-A

;;;; Level 2-A

;;;; Level 2-B

;;;; Level 3-A

;;;; Level 3-B

;;; 1-B

```

Having point on "Level 3-B" heading and using `outline-move-subtree-up` causes the whole subtree to move up to beginning of buffer, like so:

```
;;;; Level 3-B

;;; Level 1-A

;;;; Level 2-A

;;;; Level 2-B

;;;; Level 3-A

;;; 1-B

```
After that, calling `outline-move-subtree-down` moves the subtree back where it was (ie, it does not move does one position at a time).

I am using Emacs 25.0.92 on OS X 10.10

**Comment by vsrepo** [comment]
Experiencing the same here on Ubuntu 16.04 RC

**Comment by tj64** [comment]
Hi, I see the same behaviour.
The bugfix was already there in outshine, but outcommented (why?).

So I fixed this in trunk an pushed to origin. Could you/somebody please use trunk instead of master for a while and confirm that this fix does not cause trouble in other places? I spend too little time with Emacs currently to have a high chance to hit these side-effects.

When everything stays fine, I push to master.

**Comment by priyadarshan** [comment]
It is fixed. Behaviour is like expected now.
Wonderful, thank you so much for your quick reply help.
`outshine` is a gem (and `navi` too)!

**Comment by tj64** [comment]
Let me know if you experience side-effects!
Its merged into and pushed to master now.
