### ISSUE TITLE
[feature request] left margin

### ISSUE THREAD

**Issue by TLINDEN** [tj64/outshine#62]
Hi,

would it be possible to add an overlay or text-property (like org-mode does) like this:

say we have the following:
```
;; * Heading
(defun blah()
  (dosomething))
```
display as:
```
;; * Heading
     (defun blah()
       (dosomething))
```
so that the content inside a heading is aligned to the actual heading?

This would enhance readability a lot.

Thanks,
Tom

**Comment by tj64** [comment]
Hi,
Does Org-mode really implement this? 

I don't think it's a good idea for programming modes, so I won't do that.
But its probably just about indentation rules, maybe there are means to customize them?


Von meinem Samsung Galaxy Smartphone gesendet.

-------- Ursprüngliche Nachricht --------
Von: TLINDEN <notifications@github.com> 
Datum:03.05.2016  12:31  (GMT+01:00) 
An: tj64/outshine <outshine@noreply.github.com> 
Cc:  
Betreff: [tj64/outshine] [feature request] left margin (#62) 

Hi, would it be possible to add an overlay (or however org-mode implements this) like this: say we have the following: ;; * Heading (defun blah() (dosomething)) display as: ;; * Heading (defun blah() (dosomething)) so that the content inside a heading is aligned to the actual heading? This would enhance readability a lot. Thanks, Tom —You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by TLINDEN** [comment]
Well, it's indentation in org-mode, so that's of course not what I want. Instead I'd like to have it apply a text-property (or an overlay) so that it /looks/ indented (while in reality it doesn't touch the text).

**Comment by tj64** [comment]
Thats a pretty exotic idea ...

**Comment by TLINDEN** [comment]
The feature is such exotic that the org mode manual even offers a whole chapter on the issue: http://orgmode.org/manual/Clean-view.html.

- Tom

**Comment by tj64** [comment]
Ok, now I know what you mean, since I don't use clean view, I forgot about it.

Maybe it's doable, I won't be able to help you with this. Remember that outshine is a major-mode agnostic minor-mode, so things are a bit different compared to org-mode.



Von meinem Samsung Galaxy Smartphone gesendet.

-------- Ursprüngliche Nachricht --------
Von: TLINDEN <notifications@github.com> 
Datum:05.05.2016  13:52  (GMT+01:00) 
An: tj64/outshine <outshine@noreply.github.com> 
Cc: Thorsten <defvar.name@gmail.com>, State change <state_change@noreply.github.com> 
Betreff: Re: [tj64/outshine] [feature request] left margin (#62) 

The feature is such exotic that the org mode manual even offers a whole chapter on the issue: http://orgmode.org/manual/Clean-view.html. Tom —You are receiving this because you modified the open/close state.Reply to this email directly or view it on GitHub
