### ISSUE TITLE
Outshine breaks describe-key

### ISSUE THREAD

**Issue by rgrinberg** [tj64/outshine#65]
In emacs-lisp mode for example, doing `describe-key` on tab gives me the following error:

```
describe-key: Wrong type argument: symbolp, #[(&optional arg) "o
Ä 
Ä Å	!ÆÇÈ!É1'Ê!0)Æ*" [outshine-org-style-global-cycling-at-bob-p arg outline-minor-mode original-func outline-on-heading-p outline-cycle nil key-binding "	" (error) ...] 2 nil "P"]

```

**Comment by tj64** [comment]
Well. outshine does some macro magic around keybindings, especially TAB ...
Is that a general problem, or just this one key?

And maybe its not even an error, but just reflecting the situation: keybindings are not directly assigned, but a macro is called to decide which keybinding to use.

I try next time I boot my Linux machine with Emacs ...

**Comment by alphapapa** [comment]
Hm, I just ran `M-x describe-key TAB` in an elisp buffer and it worked:

```
TAB (translated from <tab>) runs the command outline-cycle, which is
an interactive Lisp function in `outshine.el'.

It is bound to TAB, <menu-bar> <Outshine> <Cycle Subtree>.

(outline-cycle &optional ARG)

Visibility cycling for outline(-minor)-mode.
```

**Comment by rgrinberg** [comment]
On 04/02, alphapapa wrote:
>Hm, I just ran `M-x describe-key TAB` in an elisp buffer and it worked:

Hmm, I wonder how I should debug this.

**Comment by alphapapa** [comment]
Here's what I recommend:

1.  Keeping a copy of your `~/.emacs.d` directory, delete all `.elc` files in it recursively, then restart Emacs and try again.  Just today I spent...too much time...trying to figure out a very weird Helm issue that turned out to be caused by stale `.elc` files.  I don't know how, because they should be ignored when there's a newer version of the package, but sometimes it happens.

2.  If that doesn't fix it, then if you're comfortable with upgrading all of your MELPA packages at once (seems like most people do that), I'd suggest doing that, then restarting Emacs and seeing if it fixes it.  

3.  If not, please try running `emacs -Q`, then run `package-initialize`, then load an elisp file, activate Outshine, and do `describe-key` again.  If that fixes it, then I guess something in your init file is causing it, in which case the `bug-hunter` package might help you narrow it down.

If none of that fixes it, I will be quite perplexed, and we'll have to dig further.  :)

**Comment by rgrinberg** [comment]
This was actually a bug in Emacs itself introduced and later fixed in master. The bug was that binding keys to lambdas was breaking describe-key. I guess I only saw this with outshine because it's rare for plugins not to use named functions for this.
